import { Measurement } from "@/types";

export const MP_MEASUREMENTS: Measurement[] = [
  // Seed & Crop (Agriculture)
  {
    id: "mp-agri-1",
    slug: "mp-ratti-agri",
    name_english: "Ratti",
    name_hindi: "रत्ती",
    name_sanskrit: "Raktikā",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Smallest traditional weight unit for seeds.",
    category: "weight",
    sector: "agriculture",
    modern_equivalent: "≈0.1215 g",
    conversion_formula: "Base Unit",
    states: ["Madhya Pradesh"],
    used_in: ["Weighing seeds, medicinal herbs and spices"],
    references: ["Arthashastra; Charaka Samhita"],
  },
  {
    id: "mp-agri-2",
    slug: "mp-masha-agri",
    name_english: "Masha",
    name_hindi: "माशा",
    name_sanskrit: "Māṣa",
    local_names: ["माशा (Masha)"],
    meaning: "Small agricultural weight.",
    category: "weight",
    sector: "agriculture",
    modern_equivalent: "≈0.972 g",
    conversion_formula: "8 Ratti = 1 Masha",
    states: ["Madhya Pradesh"],
    used_in: ["Seeds, herbs, agricultural produce"],
    references: ["Arthashastra"],
  },
  {
    id: "mp-agri-3",
    slug: "mp-tola-agri",
    name_english: "Tola",
    name_hindi: "तोला",
    name_sanskrit: "Tulā",
    local_names: ["तोला (Tola)"],
    meaning: "Standard traditional weight.",
    category: "weight",
    sector: "agriculture",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    states: ["Madhya Pradesh"],
    used_in: ["Oilseeds, spices, valuable produce"],
    references: ["British India Standards"],
  },

  // Trade & Commerce
  {
    id: "mp-trade-1",
    slug: "mp-chhatak-trade",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक (Chhatak)"],
    meaning: "Retail weight.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    states: ["Madhya Pradesh"],
    used_in: ["Grocery items"],
    references: ["Central Provinces Gazetteers"],
  },
  {
    id: "mp-trade-2",
    slug: "mp-pav-trade",
    name_english: "Pav (Pao)",
    name_hindi: "पाव",
    local_names: ["पाव (Pav)"],
    meaning: "Quarter Seer.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈233 g",
    conversion_formula: "4 Chhatak = 1 Pav",
    states: ["Madhya Pradesh"],
    used_in: ["Flour, sugar, pulses"],
    references: ["MP District Gazetteers"],
  },

  // Textile & Handloom
  {
    id: "mp-tex-1",
    slug: "mp-angul-tex",
    name_english: "Angul",
    name_hindi: "अंगुल",
    name_sanskrit: "Aṅgula",
    local_names: ["अंगुल (Angul)"],
    meaning: "Finger-width measurement.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈1.9 cm",
    conversion_formula: "Base Unit",
    states: ["Madhya Pradesh"],
    used_in: ["Measuring thread, cloth borders"],
    references: ["Arthashastra; Manasara"],
  },
  {
    id: "mp-tex-2",
    slug: "mp-gaz-tex",
    name_english: "Gaz (Gaj)",
    name_hindi: "गज़",
    local_names: ["गज़ (Gaz)"],
    meaning: "Standard cloth measure.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈0.9144 m",
    conversion_formula: "Regional standard",
    states: ["Madhya Pradesh"],
    used_in: ["Cloth trade, tailoring"],
    references: ["Imperial Gazetteer"],
  },

  // Medicine (Ayurveda)
  {
    id: "mp-med-1",
    slug: "mp-karsha-med",
    name_english: "Karsha",
    name_hindi: "कर्ष",
    name_sanskrit: "Karṣa",
    local_names: ["कर्ष (Karsha)"],
    meaning: "Common medicinal dose.",
    category: "weight",
    sector: "medicine",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Karsha",
    states: ["Madhya Pradesh"],
    used_in: ["Churna, Kalka"],
    references: ["Charaka Samhita"],
  },
  {
    id: "mp-med-2",
    slug: "mp-pala-med",
    name_english: "Pala",
    name_hindi: "पल",
    name_sanskrit: "Pala",
    local_names: ["पल (Pala)"],
    meaning: "Standard pharmacy unit.",
    category: "weight",
    sector: "medicine",
    modern_equivalent: "≈46.6 g",
    conversion_formula: "4 Karsha = 1 Pala",
    states: ["Madhya Pradesh"],
    used_in: ["Oils, decoctions"],
    references: ["Ashtanga Hridaya"],
  },

  // Construction & Architecture
  {
    id: "mp-arch-1",
    slug: "mp-vitasti-arch",
    name_english: "Vitasti",
    name_hindi: "वितस्ति",
    name_sanskrit: "Vitasti",
    local_names: ["वितस्ति (Vitasti)"],
    meaning: "Span measurement.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈22.8 cm",
    conversion_formula: "12 Angula = 1 Vitasti",
    states: ["Madhya Pradesh"],
    used_in: ["Pillars, walls"],
    references: ["Samarangana Sutradhara"],
  },
  {
    id: "mp-arch-2",
    slug: "mp-hasta-arch",
    name_english: "Hasta",
    name_hindi: "हस्त",
    name_sanskrit: "Hasta",
    local_names: ["हस्त (Hasta)"],
    meaning: "Cubit.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈45.6 cm",
    conversion_formula: "2 Vitasti = 1 Hasta (24 Angula)",
    states: ["Madhya Pradesh"],
    used_in: ["Building dimensions"],
    references: ["Mayamata"],
  },

  // Transportation & Distance
  {
    id: "mp-trans-1",
    slug: "mp-danda-trans",
    name_english: "Danda",
    name_hindi: "दण्ड",
    name_sanskrit: "Daṇḍa",
    local_names: ["दण्ड (Danda)"],
    meaning: "Measuring rod used for roads and layouts.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈1.82 m",
    conversion_formula: "4 Hasta = 1 Danda",
    states: ["Madhya Pradesh"],
    used_in: ["Roads, bridges, layouts"],
    references: ["Arthashastra"],
  },
  {
    id: "mp-trans-2",
    slug: "mp-krosha-trans",
    name_english: "Krosha (Kos)",
    name_hindi: "क्रोश / कोस",
    name_sanskrit: "Krośa",
    local_names: ["कोस (Kos)"],
    meaning: "Traditional road distance.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈3.2 km",
    conversion_formula: "1 Kos = 2000 Danda",
    states: ["Madhya Pradesh"],
    used_in: ["Road travel, milestones"],
    references: ["Arthashastra; Imperial Gazetteer"],
  },
  {
    id: "mp-trans-3",
    slug: "mp-yojana-trans",
    name_english: "Yojana",
    name_hindi: "योजन",
    name_sanskrit: "Yojana",
    local_names: ["योजन (Yojana)"],
    meaning: "Largest traditional distance unit.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈12.8 km",
    conversion_formula: "4 Kos = 1 Yojana",
    states: ["Madhya Pradesh"],
    used_in: ["Long-distance travel"],
    references: ["Surya Siddhanta; Arthashastra"],
  },

  // Livestock & Dairy
  {
    id: "mp-dairy-1",
    slug: "mp-pav-dairy",
    name_english: "Pav (Pao)",
    name_hindi: "पाव",
    local_names: ["पाव (Pav)"],
    meaning: "Quarter Seer.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈233 g / ≈250 ml",
    conversion_formula: "4 Chhatak = 1 Pav",
    states: ["Madhya Pradesh"],
    used_in: ["Milk and curd"],
    references: ["Mughal-1958"],
  },
  {
    id: "mp-dairy-2",
    slug: "mp-seer-dairy",
    name_english: "Seer",
    name_hindi: "सेर",
    local_names: ["सेर (Seer)"],
    meaning: "Standard dairy measure.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈0.933 kg / ≈0.93 L",
    conversion_formula: "2 Half Seer = 1 Seer",
    states: ["Madhya Pradesh"],
    used_in: ["Milk, ghee, fodder"],
    references: ["Imperial Gazetteer"],
  },

  // Household & Daily Life
  {
    id: "mp-hh-1",
    slug: "mp-chhatak-hh",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक (Chhatak)"],
    meaning: "Small domestic measure.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    states: ["Madhya Pradesh"],
    used_in: ["Sugar, flour, lentils"],
    references: ["Central Provinces Gazetteers"],
  },
  {
    id: "mp-hh-2",
    slug: "mp-maund-hh",
    name_english: "Maund (Man)",
    name_hindi: "मन",
    local_names: ["मन (Man)"],
    meaning: "Bulk storage unit.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seers = 1 Maund",
    states: ["Madhya Pradesh"],
    used_in: ["Household grain storage"],
    references: ["Mughal-1958"],
  },

  // Gold & Jewellery
  {
    id: "mp-gold-1",
    slug: "mp-suvarna-gold",
    name_english: "Suvarna",
    name_hindi: "सुवर्ण",
    name_sanskrit: "Suvarṇa",
    local_names: ["सुवर्ण (Suvarna)"],
    meaning: "Classical gold unit.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈15.55 g",
    conversion_formula: "16 Masha = 1 Suvarna",
    states: ["Madhya Pradesh"],
    used_in: ["Gold coins and ornaments"],
    references: ["Arthashastra"],
  },
  {
    id: "mp-gold-2",
    slug: "mp-tola-gold",
    name_english: "Tola",
    name_hindi: "तोला",
    name_sanskrit: "Tulā",
    local_names: ["तोला (Tola)"],
    meaning: "Standard jewellers' unit.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    states: ["Madhya Pradesh"],
    used_in: ["Gold and silver trade"],
    references: ["British India Standards"],
  },

  // Currency & Money
  {
    id: "mp-cur-1",
    slug: "mp-cowrie-cur",
    name_english: "Cowrie",
    name_hindi: "कौड़ी",
    name_sanskrit: "Kapardikā",
    local_names: ["कौड़ी (Cowrie)"],
    meaning: "Smallest medium of exchange.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "No fixed SI equivalent",
    conversion_formula: "Base unit",
    states: ["Madhya Pradesh"],
    used_in: ["Petty transactions"],
    references: ["Arthashastra; Numismatic Studies"],
  },
  {
    id: "mp-cur-2",
    slug: "mp-rupee-cur",
    name_english: "Rupee",
    name_hindi: "रुपया",
    name_sanskrit: "Rūpya",
    local_names: ["रुपया (Rupee)"],
    meaning: "Standard monetary unit.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Historical silver coin",
    conversion_formula: "16 Anna = 1 Rupee",
    states: ["Madhya Pradesh"],
    used_in: ["Trade, taxation, salaries"],
    references: ["Arthashastra; Imperial Gazetteer"],
  },
  {
    id: "mp-cur-3",
    slug: "mp-mohur-cur",
    name_english: "Mohur",
    name_hindi: "मोहर",
    name_sanskrit: "Suvarṇa Mudrā",
    local_names: ["मोहर (Mohur)"],
    meaning: "Gold currency.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Gold coin",
    conversion_formula: "Value varied with gold content",
    states: ["Madhya Pradesh"],
    used_in: ["High-value trade"],
    references: ["Numismatic Society of India"],
  },

  // Storage & Transportation
  {
    id: "mp-storage-1",
    slug: "mp-chhatak-storage",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक (Chhatak)"],
    meaning: "Small storage unit.",
    category: "weight",
    sector: "storage-transport",
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    states: ["Madhya Pradesh"],
    used_in: ["Small quantities of grain, spices"],
    references: ["Central Provinces Gazetteers"],
  },
  {
    id: "mp-storage-2",
    slug: "mp-khandi-storage",
    name_english: "Khandi",
    name_hindi: "खंडी",
    name_sanskrit: "Khaṇḍī",
    local_names: ["खंडी (Khandi)"],
    meaning: "Largest traditional storage unit.",
    category: "volume",
    sector: "storage-transport",
    modern_equivalent: "≈746 kg",
    conversion_formula: "≈20 Maunds = 1 Khandi (Regional)",
    states: ["Madhya Pradesh"],
    used_in: ["Warehouse storage and long-distance transport"],
    references: ["Madhya Pradesh District Gazetteers"],
  },

  // Land Measurement
  {
    id: "mp-land-1",
    slug: "mp-square-gaj",
    name_english: "Square Gaj",
    name_hindi: "वर्ग गज़",
    name_sanskrit: "Gaja",
    local_names: ["Square Gaj"],
    meaning: "Smallest commonly used area unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "≈0.8361 m²",
    conversion_formula: "Base Unit",
    states: ["Madhya Pradesh"],
    used_in: ["House plots and small land parcels"],
    references: ["Imperial Gazetteer of India"],
  },
  {
    id: "mp-land-2",
    slug: "mp-bigha",
    name_english: "Bigha",
    name_hindi: "बीघा",
    local_names: ["बीघा (Bigha)"],
    meaning: "Principal traditional land unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "≈0.25–0.67 hectare",
    conversion_formula: "20 Biswa = 1 Bigha",
    states: ["Madhya Pradesh"],
    used_in: ["Agricultural fields"],
    references: ["Imperial Gazetteer; MP Gazetteers"],
  },
  {
    id: "mp-land-3",
    slug: "mp-acre-land",
    name_english: "Acre",
    name_hindi: "एकड़",
    local_names: ["एकड़ (Acre)"],
    meaning: "British standard land unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "4046.86 m²",
    conversion_formula: "1 Acre = 4840 sq yd",
    states: ["Madhya Pradesh"],
    used_in: ["Revenue and settlement records"],
    references: ["British Revenue Records"],
  }
];
