/**
 * Rebuilds lib/unitPhotos.ts from scripts/unit-photos.json
 * (one entry per photo pasted in the "DESINAAP Real Image Checklist" documents).
 *
 *   npx tsx scripts/build-unit-photos.ts
 *
 * Extra fields in unit-photos.json: "credit" (shown under the photo) and
 * "sectorOnly": true (the photo is only used in its own sector).
 * "file": null  = this unit has NO photo in this sector (blocks photos from other sectors too).
 *
 * Matching rules
 *  1. A unit uses the photo pasted for it in its OWN sector.
 *  2. Otherwise, a unit with the same name (or one of the listed "also called"
 *     names) in another sector uses that photo – but only if it measures the
 *     same kind of thing (so "Pal" the time unit never gets the "Pala" weight photo).
 */
import fs from "fs";
import path from "path";
import { SAMPLE_MEASUREMENTS as S } from "../lib/data";

type Row = { sector: string; unit: string; keys: string[]; file: string | null; what: string; source: string | null; credit?: string; sectorOnly?: boolean };
const rows: Row[] = JSON.parse(fs.readFileSync(path.join(__dirname, "unit-photos.json"), "utf8"));

// Different units that only share a short alias with a photographed unit
const NEVER_MATCH: Array<[RegExp, string]> = [[/karshapana/i, "Fanam (Panam)"]];

function mkeys(name: string) {
  const full = name.toLowerCase().trim();
  const base = full.replace(/\s*\([^)]*\)/g, "").trim();
  const parts = base.split(/\s*\/\s*/).map((p) => p.trim()).filter(Boolean);
  return { full, base, first: parts[0], parts };
}
function score(name: string, r: Row): number {
  if (NEVER_MATCH.some(([re, unit]) => re.test(name) && r.unit === unit)) return 0;
  const k = mkeys(name);
  const set = new Set(r.keys);
  if (set.has(k.full)) return 5;
  if (set.has(k.base)) return 4;
  if (k.first && set.has(k.first)) return 3;
  if (k.parts.some((p) => set.has(p))) return 2;
  return 0;
}

// "capacity" and "volume" mean the same thing in the data
const cat = (c: string) => (c === "capacity" ? "volume" : c);
const rowCats = new Map<Row, Set<string>>();
for (const r of rows) {
  const cats = new Set<string>();
  for (const m of S) if (m.sector === r.sector && score(m.name_english, r) > 0) cats.add(cat(m.category));
  rowCats.set(r, cats);
}

const files = Array.from(new Set(rows.map((r) => r.file).filter((f): f is string => !!f)));
const fileIdx = new Map(files.map((f, i) => [f, i]));
const bySlug: Record<string, number> = {};
let own = 0, shared = 0;
for (const m of S) {
  let best: Row | null = null, bs = 0;
  for (const r of rows) if (r.sector === m.sector) { const s = score(m.name_english, r); if (s > bs) { bs = s; best = r; } }
  if (best) {
    if (best.file) { bySlug[m.slug] = fileIdx.get(best.file)!; own++; }
    continue; // a "file": null row means: no photo for this unit here
  }
  for (const r of rows) {
    const s = score(m.name_english, r);
    const cats = rowCats.get(r)!;
    if (r.sectorOnly || !r.file) continue; // e.g. the cloth-and-tape Gaz photo belongs to Textile only
    if (s > bs && (cats.size === 0 || cats.has(cat(m.category)))) { bs = s; best = r; }
  }
  if (best && best.file) { bySlug[m.slug] = fileIdx.get(best.file)!; shared++; }
}
const photos = files.map((f) => {
  const r = rows.find((x) => x.file === f)!;
  return { src: f, unit: r.unit, what: r.what, source: r.source, credit: r.credit ?? "DESINAAP team photo" };
});

fs.writeFileSync(
  path.join(__dirname, "..", "lib", "unitPhotos.ts"),
  `// AUTO-GENERATED by scripts/build-unit-photos.ts – do not edit by hand.
// Real photos collected by the DESINAAP team (Real Image Checklist documents).
// These take priority over every other image on the site.
// To swap a photo, replace the file in public/images/units/<sector>/ and keep its name.

export interface UnitPhoto { src: string; unit: string; what: string; source: string | null; credit: string }

export const UNIT_PHOTOS: UnitPhoto[] = ${JSON.stringify(photos, null, 1)};

/** measurement slug → index in UNIT_PHOTOS */
export const UNIT_PHOTO_BY_SLUG: Record<string, number> = ${JSON.stringify(bySlug)};
`
);
const usedFiles = new Set(Object.values(bySlug));
const unused = photos.filter((_, i) => !usedFiles.has(i)).map((p) => p.unit);
if (unused.length) console.log("Photos not matched to any unit:", unused.join(", "));
console.log(`Photos: ${photos.length}. Units with a team photo: ${own + shared} (own sector ${own}, same unit elsewhere ${shared}).`);
